name: BindCraft
channels:
  - conda-forge
  - nvidia
  - https://conda.graylab.jhu.edu
dependencies:
  - pip
  - pandas
  - matplotlib
  - numpy<2.0.0
  - biopython
  - scipy
  - pdbfixer
  - seaborn
  - libgfortran5
  - tqdm
  - jupyter
  - ffmpeg
  - pyrosetta
  - fsspec
  - py3dmol
  - chex
  - dm-haiku
  - flax<0.10.0
  - dm-tree
  - joblib
  - ml-collections
  - immutabledict
  - optax
  - cuda-nvcc
  - cudnn
  - pip:
      - colabdesign
      - jax[cuda12]==0.4.34
      - jax-cuda12-pjrt==0.4.34
      - jax-cuda12-plugin[with-cuda]==0.4.34 
      - jaxlib==0.4.34
